name: nhan_dang_app
description: Ứng dụng nhận dạng đối tượng trên ảnh - Flutter Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0          # Loading animations
  
  # State Management
  provider: ^6.1.1                  # State management
  
  # HTTP & API
  dio: ^5.4.0                       # HTTP client
  http: ^1.1.2                      # Alternative HTTP
  
  # Image Handling
  image_picker: ^1.0.7              # Chọn ảnh từ gallery/camera
  camera: ^0.10.5                   # Camera access
  cached_network_image: ^3.3.0     # Cache ảnh từ server
  
  # Storage
  shared_preferences: ^2.2.2        # Local storage
  path_provider: ^2.1.1             # File paths
  
  # Utils
  intl: ^0.18.1                     # Date/time formatting
  uuid: ^4.2.2                      # UUID generation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

